spring:
  datasource:
    url: jdbc:mysql://mysql:3306/account_center?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: chat2think
    password: chat2think_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: redis
    port: 6379
    password: chat2think_redis_password
  messages:
    basename: i18n/messages
    encoding: UTF-8
  main:
    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 8080

app:
  jwt:
    secret: chat2think-secret-key
    expiration: 86400000 # 24 hours
  image:
    upload:
      dir: uploads/images/
    models:
      - name: stable-diffusion
        api-url: http://localhost:7860
      - name: dalle
        api-url: https://api.openai.com/v1/images/generations
        api-key: ${OPENAI_API_KEY}
        model: dall-e-3

